server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# -------- Resilience4j --------
resilience4j:

  retry:
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - feign.FeignException
          - java.io.IOException
        ignoreExceptions:
          - com.ms.order_service.exception.UserNotFoundException

  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

# -------- Logging --------
logging:
  level:
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG